# Generated by Django 2.1.2 on 2018-11-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='null', max_length=128),
            preserve_default=False,
        ),
    ]
